Repository softeerbootcamp-6th/Team5-HyFive, pull requests merged in 2025-07, with the labels that each got.

#6 [ Chore/#4 ] FE 개발 환경 세팅
  frontend/.gitignore
  frontend/eslint.config.js
  frontend/index.html
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/prettier.config.js
  frontend/src/App.tsx
  frontend/src/main.tsx
  frontend/src/vite-env.d.ts
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: FE, ⚙️ chore, 🐤 FE - 유재민, 🐿️ FE - 김민정

#18 [ Style/#7 ] - 디자인 시스템 구축
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/App.tsx
  frontend/src/assets/icon/ic_24_admin_calender_default.svg
  frontend/src/assets/icon/ic_24_admin_call_default.svg
  frontend/src/assets/icon/ic_24_admin_email_default.svg
  frontend/src/assets/icon/ic_24_admin_info_default.svg
  frontend/src/assets/icon/ic_24_admin_pay_default.svg
  frontend/src/assets/icon/ic_24_admin_refreash_default.svg
  frontend/src/assets/icon/ic_24_admin_search_default.svg
  frontend/src/assets/icon/ic_24_center_add_default.svg
  frontend/src/assets/icon/ic_24_center_check_default.svg
  frontend/src/assets/icon/ic_24_center_chevron-left_default.svg
  frontend/src/assets/icon/ic_24_center_chevron-right_default.svg
  frontend/src/assets/icon/ic_24_center_graph_default.svg
  frontend/src/assets/icon/ic_24_lending_eye_default.svg
  frontend/src/assets/icon/ic_24_location_admin_default.svg
  frontend/src/assets/icon/ic_24_navigation_car_default.svg
  frontend/src/assets/icon/ic_24_navigation_dashboard_default.svg
  frontend/src/assets/icon/ic_24_navigation_person_default.svg
  frontend/src/assets/icon/ic_24_navigation_route_default.svg
  frontend/src/assets/icon/ic_32_admin_car_default.svg
  frontend/src/assets/icon/ic_32_center_add_default.svg
  frontend/src/assets/icon/ic_32_center_check_default.svg
  frontend/src/assets/icon/index.ts
  frontend/src/styles/themes.style.ts
  frontend/src/vite-env.d.ts
  frontend/tsconfig.app.json
  frontend/vite.config.ts
Labels: FE, 🎨 style, 🐤 FE - 유재민, 🐿️ FE - 김민정

#24 [ Feat/#20 ] page routing 구현
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/App.tsx
  frontend/src/pages/admin/drivers.tsx
  frontend/src/pages/admin/index.tsx
  frontend/src/pages/admin/register.tsx
  frontend/src/pages/admin/reservation/index.tsx
  frontend/src/pages/admin/reservation/paths.tsx
  frontend/src/pages/admin/reservation/schedule.tsx
  frontend/src/pages/admin/reservation/users.tsx
  frontend/src/pages/admin/vehicles/[centerId].tsx
  frontend/src/pages/admin/vehicles/index.tsx
  frontend/src/pages/center/index.tsx
  frontend/src/pages/center/register.tsx
  frontend/src/pages/index.tsx
  frontend/src/pages/notFound.tsx
  frontend/src/routes/index.tsx
Labels: FE, ✨ feature, 🐤 FE - 유재민, 🐿️ FE - 김민정

#37 [ Feat/#19 ] 페이지별 레이아웃 분리 및 라우팅
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/layouts/AdminHeader.tsx
  frontend/src/components/layouts/CenterHeader.tsx
  frontend/src/components/layouts/Sidebar.tsx
  frontend/src/layouts/AdminLayout.tsx
  frontend/src/layouts/CenterLayout.tsx
  frontend/src/layouts/ReservationLayout.tsx
  frontend/src/layouts/index.ts
  frontend/src/pages/admin/adminPage.tsx
  frontend/src/pages/admin/adminRegisterPage.tsx
  frontend/src/pages/admin/drivers.tsx
  frontend/src/pages/admin/driversPage.tsx
  frontend/src/pages/admin/index.tsx
  frontend/src/pages/admin/register.tsx
  frontend/src/pages/admin/reservation/index.tsx
  frontend/src/pages/admin/reservation/paths.tsx
  frontend/src/pages/admin/reservation/pathsPage.tsx
  frontend/src/pages/admin/reservation/reservationPage.tsx
  frontend/src/pages/admin/reservation/schedule.tsx
  frontend/src/pages/admin/reservation/schedulePage.tsx
  frontend/src/pages/admin/reservation/users.tsx
  frontend/src/pages/admin/reservation/usersPage.tsx
  frontend/src/pages/admin/vehicles/[centerId].tsx
  frontend/src/pages/admin/vehicles/centerDetailPage.tsx
  frontend/src/pages/admin/vehicles/index.tsx
  frontend/src/pages/admin/vehicles/vehiclesPage.tsx
  frontend/src/pages/center/centerPage.tsx
  frontend/src/pages/center/centerRegisterPage.tsx
  frontend/src/pages/center/index.tsx
  frontend/src/pages/center/register.tsx
  frontend/src/pages/index.ts
  frontend/src/pages/index.tsx
  frontend/src/pages/landingPage.tsx
  frontend/src/pages/notFound.tsx
  frontend/src/pages/notFoundPage.tsx
  frontend/src/routes/index.tsx
Labels: FE, ✨ feature, 🐤 FE - 유재민, 🐿️ FE - 김민정
