Repository softeerbootcamp-6th/Team5-HyFive, pull requests merged in 2025-08, with the labels that each got.

#45 [ Chore/#44 ] 페이지명 변경 및 추가된 스타일 반영
  frontend/src/pages/admin/adminPage.tsx
  frontend/src/pages/admin/book/BookPage.tsx
  frontend/src/pages/admin/book/PathsPage.tsx
  frontend/src/pages/admin/book/SchedulePage.tsx
  frontend/src/pages/admin/book/UsersPage.tsx
  frontend/src/pages/admin/centers/CenterDetailPage.tsx
  frontend/src/pages/admin/centers/CentersPage.tsx
  frontend/src/pages/admin/reservation/reservationPage.tsx
  frontend/src/pages/admin/vehicles/vehiclesPage.tsx
  frontend/src/pages/index.ts
  frontend/src/routes/index.tsx
  frontend/src/styles/themes.style.ts
Labels: FE, 🎨 style, ⚙️ chore, 🐤 FE - 유재민, 🐿️ FE - 김민정

#47 [ Feat/#30 ] 공통 컴포넌트 구현
  frontend/src/assets/icons/arrow-right.svg
  frontend/src/assets/icons/dot.svg
  frontend/src/assets/icons/index.ts
  frontend/src/components/Search/SearchInput.tsx
  frontend/src/components/button/Button.tsx
  frontend/src/components/chip/Chip.tsx
  frontend/src/components/layouts/Sidebar.tsx
  frontend/src/components/statusCard/BookCard.tsx
  frontend/src/components/statusCard/DrivingCard.tsx
  frontend/src/components/table/Table.tsx
  frontend/src/components/table/TableWithIndex.tsx
  frontend/src/hooks/usePressDetection.ts
  frontend/src/layouts/BookLayout.tsx
  frontend/src/layouts/ReservationLayout.tsx
  frontend/src/layouts/index.ts
  frontend/src/mocks/bookMocks.ts
  frontend/src/mocks/drivingMocks.ts
  frontend/src/mocks/routeMocks.ts
  frontend/src/mocks/tableMocks.ts
  frontend/src/mocks/usersMocks.ts
  frontend/src/pages/TestPage.tsx
  frontend/src/pages/admin/adminRegisterPage.tsx
  frontend/src/pages/index.ts
  frontend/src/routes/index.tsx
  frontend/src/styles/global.style.css
  frontend/src/styles/reset.style.css
  frontend/src/styles/themes.style.ts
  frontend/src/types/bookType.d.ts
  frontend/src/types/drivingType.d.ts
  frontend/src/types/routeType.d.ts
  frontend/src/types/usersType.d.ts
  frontend/src/utils/TableMatcher.ts
  frontend/tsconfig.app.json
Labels: FE, ✨ feature, 🎨 style, 🐿️ FE - 김민정

#52 [ Feat/#31 ] 공통 컴포넌트 구현
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/assets/icons/index.ts
  frontend/src/assets/icons/logo_default.svg
  frontend/src/components/common/DropdownInput.tsx
  frontend/src/components/common/Input.tsx
  frontend/src/components/common/RadioGroup.tsx
  frontend/src/components/common/Tabs.tsx
  frontend/src/components/common/Tag.tsx
  frontend/src/components/common/ToggleButton.tsx
  frontend/src/components/layouts/AdminHeader.tsx
  frontend/src/components/layouts/CenterHeader.tsx
  frontend/src/components/layouts/Header.tsx
  frontend/src/layouts/AdminLayout.tsx
  frontend/src/layouts/CenterLayout.tsx
  frontend/src/pages/TestPage.tsx
  frontend/src/routes/index.tsx
  frontend/src/styles/reset.style.css
  frontend/src/styles/themes.style.ts
Labels: FE, ✨ feature, 🐤 FE - 유재민

#51 [ Chore/#41 ] frontend ci 구축
  .github/workflows/frontend-ci.yml
  .gitignore
  frontend/.prettierignore
  frontend/eslint.config.js
  frontend/package.json
  frontend/src/assets/icons/index.ts
  frontend/src/components/DropdownInput.tsx
  frontend/src/components/Input.tsx
  frontend/src/components/RadioGroup.tsx
  frontend/src/components/layouts/Header.tsx
  frontend/src/hooks/usePressDetection.ts
  frontend/src/pages/LandingPage.tsx
  frontend/src/pages/NotFoundPage.tsx
  frontend/src/pages/admin/AdminRegisterPage.tsx
  frontend/src/pages/admin/DriversPage.tsx
  frontend/src/pages/center/CenterPage.tsx
  frontend/src/pages/center/CenterRegisterPage.tsx
  frontend/src/routes/index.tsx
  frontend/tsconfig.app.json
Labels: FE, ⚙️ chore, 🐿️ FE - 김민정

#81 [ Docs/#57 ] 이슈 템플릿 양식 변경
  .github/ISSUE_TEMPLATE/feature-issue.md
Labels: 📝 docs, 🐙 BE - 신지수

#85 [ Docs/#83 ] PR 템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📝 docs, 🐙 BE - 신지수

#90 [ Feat/#82 ] 실시간 예약 현황 페이지: 전체 예약 리스트 및 개별 예약 정보 컴포넌트 구현
  frontend/src/assets/gif/moving_car.gif
  frontend/src/assets/icons/index.ts
  frontend/src/assets/icons/no-route.svg
  frontend/src/components/RefetchButton.tsx
  frontend/src/components/Tabs.tsx
  frontend/src/components/layouts/Sidebar.tsx
  frontend/src/features/book/Book.types.ts
  frontend/src/features/book/BookCard.style.ts
  frontend/src/features/book/BookCard.tsx
  frontend/src/features/book/BookDetailSection.tsx
  frontend/src/features/book/BookListSection.tsx
  frontend/src/features/book/RouteCard.tsx
  frontend/src/layouts/BookLayout.tsx
  frontend/src/pages/admin/book/BookPage.tsx
  frontend/src/utils/DateFormatter.ts
  frontend/src/utils/TabMatcher.ts
Labels: FE, ✨ feature, 🎨 style, 🐿️ FE - 김민정

#107 [ Feat/#101 ] 차량 등록 `POST /api/car` 구현
  backend/src/main/java/hyfive/gachita/car/Car.java
  backend/src/main/java/hyfive/gachita/car/CarController.java
  backend/src/main/java/hyfive/gachita/car/CarRepository.java
  backend/src/main/java/hyfive/gachita/car/CarService.java
  backend/src/main/java/hyfive/gachita/car/dto/CarRes.java
  backend/src/main/java/hyfive/gachita/car/dto/CreateCarReq.java
  backend/src/main/java/hyfive/gachita/common/response/ErrorCode.java
  backend/src/main/java/hyfive/gachita/common/response/GlobalExceptionHandler.java
  backend/src/main/java/hyfive/gachita/common/util/CarNumberFormatter.java
  backend/src/main/java/hyfive/gachita/docs/CarDocs.java
  backend/src/main/resources/application-prod.properties
Labels: BE, ✨ feature, 🐙 BE - 신지수

#111 [Feat/#100] 예약 리스트 조회 구현
  backend/build.gradle
  backend/src/main/java/hyfive/gachita/book/BookController.java
  backend/src/main/java/hyfive/gachita/book/BookService.java
  backend/src/main/java/hyfive/gachita/book/dto/BookRes.java
  backend/src/main/java/hyfive/gachita/book/dto/CreateBookReq.java
  backend/src/main/java/hyfive/gachita/book/repository/BookRepository.java
  backend/src/main/java/hyfive/gachita/book/repository/CustomBookRepository.java
  backend/src/main/java/hyfive/gachita/book/repository/CustomBookRepositoryImpl.java
  backend/src/main/java/hyfive/gachita/common/dto/ListRes.java
  backend/src/main/java/hyfive/gachita/common/enums/SearchPeriod.java
  backend/src/main/java/hyfive/gachita/common/response/GlobalExceptionHandler.java
  backend/src/main/java/hyfive/gachita/config/CaseInsensitiveEnumConverter.java
  backend/src/main/java/hyfive/gachita/config/QueryDslConfig.java
  backend/src/main/java/hyfive/gachita/config/SwaggerConfig.java
  backend/src/main/java/hyfive/gachita/docs/BookDocs.java
Labels: BE, ✨ feature, 🙄 BE - 성유진

#115 [ Feat/#105 ] 센터 정보 컴포넌트 구현
  frontend/package.json
  frontend/src/features/CenterOverview/CenterInfoCard.tsx
  frontend/src/features/CenterOverview/CenterOverview.test.tsx
  frontend/src/features/CenterOverview/CenterOverview.tsx
  frontend/src/features/CenterOverview/CenterOverview.type.ts
  frontend/src/layouts/AdminLayout.tsx
  frontend/src/pages/admin/centers/CenterDetailPage.tsx
Labels: FE, ✨ feature, 🐤 FE - 유재민

#117 [ Chore/#91 ] frontend cd 구축
  .github/workflows/frontend-cd.yml
  .github/workflows/frontend-ci.yml
Labels: FE, ⚙️ chore, 🐿️ FE - 김민정

#116 [ Feat/#114 ] 차량 상세: `GET /api/car/{id}`
  backend/src/main/java/hyfive/gachita/car/CarController.java
  backend/src/main/java/hyfive/gachita/car/CarService.java
  backend/src/main/java/hyfive/gachita/docs/CarDocs.java
Labels: BE, ✨ feature, 🐙 BE - 신지수

#131 [Feat/#112] 예약 스크롤 조회 `GET /api/book/scroll?status=&size=&lastId=&lastCreatedAt=`
  backend/src/main/java/hyfive/gachita/book/BookController.java
  backend/src/main/java/hyfive/gachita/book/BookService.java
  backend/src/main/java/hyfive/gachita/book/BookStatus.java
  backend/src/main/java/hyfive/gachita/book/dto/BookCursor.java
  backend/src/main/java/hyfive/gachita/book/repository/CustomBookRepository.java
  backend/src/main/java/hyfive/gachita/book/repository/CustomBookRepositoryImpl.java
  backend/src/main/java/hyfive/gachita/common/dto/ScrollRes.java
  backend/src/main/java/hyfive/gachita/common/response/GlobalExceptionHandler.java
  backend/src/main/java/hyfive/gachita/docs/BookDocs.java
  backend/src/main/resources/application-init.properties
  backend/src/main/resources/book.sql
Labels: BE, ✨ feature, 🦦 BE - 성유진

#136 [ Feat/#109 ] 지도 컴포넌트 구현
  frontend/index.html
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/assets/icons/index.ts
  frontend/src/assets/icons/marker-default.svg
  frontend/src/assets/icons/marker-end.svg
  frontend/src/assets/icons/marker-enter-num.svg
  frontend/src/assets/icons/marker-enter.svg
  frontend/src/assets/icons/marker-out-num.svg
  frontend/src/assets/icons/marker-out.svg
  frontend/src/assets/icons/marker-start.svg
  frontend/src/components/Button.tsx
  frontend/src/components/FallbackUI.tsx
  frontend/src/features/map/Map.types.ts
  frontend/src/features/map/MapContent.tsx
  frontend/src/features/map/MapHeader.tsx
  frontend/src/features/map/MapSection.tsx
  frontend/src/features/map/PassengerDropDown.tsx
  frontend/src/features/map/ZoomButton.tsx
  frontend/src/features/map/useInitializeMap.ts
  frontend/src/features/map/useVisualizeMarker.ts
  frontend/src/features/map/useVisualizeRoute.ts
  frontend/src/features/map/useZoomLevel.ts
  frontend/src/features/schedule/MapContent.tsx
  frontend/src/mocks/pathMocks.ts
  frontend/src/pages/TestPage.tsx
  frontend/src/pages/admin/book/SchedulePage.tsx
  frontend/src/types/global.d.ts
  frontend/src/types/path.types.ts
Labels: FE, ✨ feature, 🐿️ FE - 김민정

#146 [ Feat/#127 ] 센터 세부 페이지 퍼블리싱
  frontend/src/components/layouts/Header.tsx
  frontend/src/features/TimeTable/TimeTable.style.ts
  frontend/src/features/TimeTable/TimeTable.test.tsx
  frontend/src/features/TimeTable/TimeTable.tsx
  frontend/src/features/calander/Calander.tsx
  frontend/src/features/calender/Calender.style.ts
  frontend/src/features/calender/Calender.test.tsx
  frontend/src/features/calender/Calender.tsx
  frontend/src/features/calender/Calender.util.ts
  frontend/src/features/calender/CalenderContent.tsx
  frontend/src/features/calender/CalenderHeader.tsx
  frontend/src/features/calender/CalenderReducer.ts
  frontend/src/mocks/centerDetailMocks.ts
  frontend/src/pages/TestPage.tsx
  frontend/src/pages/admin/centers/CenterDetailPage.tsx
Labels: FE, ✨ feature, 🐤 FE - 유재민

#167 [ Feat/#108 ] 경로 반환 기능 구현 및 테스트 코드 적용
  .github/workflows/frontend-ci.yml
  frontend/package.json
  frontend/src/features/map/Map.types.ts
  frontend/src/features/map/animateRouteSegments.test.ts
  frontend/src/features/map/animateRouteSegments.util.ts
  frontend/src/features/map/getRouteMidPoint.test.ts
  frontend/src/features/map/getRouteMidPoint.util.ts
  frontend/src/features/map/getRouteSegments.test.ts
  frontend/src/features/map/getRouteSegments.util.ts
  frontend/src/features/map/useVisualizeMarker.ts
  frontend/src/features/map/useVisualizeRoute.test.ts
  frontend/src/features/map/useVisualizeRoute.ts
  frontend/src/features/schedule/MapHeader.tsx
  frontend/src/features/schedule/PassengerDropDown.tsx
  frontend/src/features/schedule/ScheduleDetailSection.tsx
  frontend/src/pages/admin/book/SchedulePage.tsx
  frontend/src/types/global.d.ts
  frontend/src/types/path.types.ts
Labels: FE, ✨ feature, 🐿️ FE - 김민정

#145 [Feat/#142] 센터 정보 조회 `/api/center/{id}`
  backend/src/main/java/hyfive/gachita/center/Center.java
  backend/src/main/java/hyfive/gachita/center/CenterController.java
  backend/src/main/java/hyfive/gachita/center/CenterRes.java
  backend/src/main/java/hyfive/gachita/center/CenterService.java
  backend/src/main/java/hyfive/gachita/common/enums/SearchPeriod.java
  backend/src/main/java/hyfive/gachita/docs/CenterDocs.java
  backend/src/main/java/hyfive/gachita/pay/PayRepository.java
  backend/src/main/java/hyfive/gachita/pay/PayService.java
  backend/src/main/java/hyfive/gachita/pay/repository/CustomPayRepository.java
  backend/src/main/java/hyfive/gachita/pay/repository/CustomPayRepositoryImpl.java
  backend/src/main/java/hyfive/gachita/pay/repository/PayRepository.java
Labels: BE, ✨ feature, 🦦 BE - 성유진

#163 [Refactor/#104] 예외처리 리팩토링
  backend/src/main/java/hyfive/gachita/common/response/ErrorCode.java
  backend/src/main/java/hyfive/gachita/common/response/GlobalExceptionHandler.java
Labels: BE, ✨ feature, 🦦 BE - 성유진

#177 [Feat/#139] 차량 등록 페이지 퍼블리싱
  frontend/index.html
  frontend/src/assets/icons/favicon.svg
  frontend/src/assets/icons/index.ts
  frontend/src/assets/icons/remove-circle.svg
  frontend/src/components/DropdownInput.tsx
  frontend/src/components/Input.tsx
  frontend/src/features/carUploader/ImageInput.tsx
  frontend/src/features/carUploader/InputSection.tsx
  frontend/src/layouts/BookLayout.tsx
  frontend/src/layouts/CenterLayout.tsx
  frontend/src/pages/TestPage.tsx
  frontend/src/pages/center/CenterRegisterPage.tsx
  frontend/src/pages/index.ts
  frontend/src/routes/index.tsx
Labels: FE, ✨ feature, 🎨 style, 🐿️ FE - 김민정

#179 [Chore] 대소문자 구분을 위한 기존 src/feature/Car 디렉토리 삭제
  frontend/src/features/Car/Car.type.ts
  frontend/src/features/Car/CarInfoCard.style.ts
  frontend/src/features/Car/CarInfoCard.test.tsx
  frontend/src/features/Car/CarInfoCard.tsx
Labels: FE, ⚙️ chore, 🐤 FE - 유재민

#180 [Feat/#178] 차량 등록 폼: 상태 관리 및 유효성 검사
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/Button.tsx
  frontend/src/components/DropdownInput.tsx
  frontend/src/components/Input.tsx
  frontend/src/components/ToggleButton.tsx
  frontend/src/features/carUploader/InputSection.tsx
  frontend/src/features/carUploader/useCarForm.ts
  frontend/src/pages/center/CenterRegisterPage.tsx
Labels: FE, ✨ feature, 🐿️ FE - 김민정

#184 [Refactor/#181] timeTable 폴더 내 파일 리팩토링
  frontend/src/features/timeTable/PreviewTimeSlot.tsx
  frontend/src/features/timeTable/TimeTable.constants.ts
  frontend/src/features/timeTable/TimeTable.style.ts
  frontend/src/features/timeTable/TimeTable.test.tsx
  frontend/src/features/timeTable/TimeTable.tsx
  frontend/src/features/timeTable/TimeTable.type.ts
  frontend/src/features/timeTable/TimeTable.util.ts
  frontend/src/features/timeTable/components/AvailableTimeSlot.tsx
  frontend/src/features/timeTable/components/AvailableTimeSlots.tsx
  frontend/src/features/timeTable/components/TimeCell.tsx
  frontend/src/features/timeTable/components/TimeCells.tsx
  frontend/src/features/timeTable/components/TimeLabels.tsx
  frontend/src/features/timeTable/components/TimeTable.tsx
  frontend/src/features/timeTable/components/TimeTableHeader.tsx
  frontend/src/features/timeTable/components/index.ts
  frontend/src/features/timeTable/useTimeTableDrag.ts
  frontend/src/pages/admin/centers/CenterDetailPage.tsx
Labels: FE, ♻️ refactor, 🐤 FE - 유재민

#191 [Fix#185] PR 관련 yml 파일 오류 수정- FE
  .github/workflows/close-issues-when-pr-close.yml
Labels: 🛠️ fix, 🐤 FE - 유재민

#190 [Feat/#150] 차량 이미지 등록 기능 구현
  frontend/src/features/carUploader/ImageInput.styles.ts
  frontend/src/features/carUploader/ImageInput.tsx
  frontend/src/features/carUploader/ImageValidator.util.ts
  frontend/src/features/carUploader/InputSection.tsx
  frontend/src/features/carUploader/useCarForm.ts
  frontend/src/features/carUploader/useDragImage.ts
  frontend/src/features/carUploader/usePreviewImage.ts
  frontend/src/features/carUploader/useUploadImage.ts
  frontend/src/hooks/useDocumentEvent.ts
Labels: FE, ✨ feature, 🐿️ FE - 김민정

#192 [Fix#185] PR 관련 yml 파일 오류 수정- BE
  .github/workflows/close-issues-when-pr-close.yml
Labels: 🛠️ fix, 🐤 FE - 유재민

#197 [Feat/#157] 미배차 차량 배차 - 센터 필터링 기능 구현
  backend/src/main/java/hyfive/gachita/dispatch/UnDispatchService.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/CenterDispatchLocationDto.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/DispatchLocation.java
  backend/src/main/java/hyfive/gachita/dispatch/module/filter/BoundingBoxFilter.java
  backend/src/main/java/hyfive/gachita/dispatch/module/filter/Filter.java
  backend/src/main/java/hyfive/gachita/dispatch/module/filter/HaversineFilter.java
  backend/src/main/java/hyfive/gachita/dispatch/module/filter/condition/BoundingBoxCondition.java
  backend/src/main/java/hyfive/gachita/dispatch/module/filter/condition/FilterCondition.java
  backend/src/main/java/hyfive/gachita/dispatch/module/filter/condition/RadiusCondition.java
  backend/src/main/java/hyfive/gachita/dispatch/provider/CenterDispatchLocationProvider.java
  backend/src/main/java/hyfive/gachita/dispatch/provider/DispatchLocationProvider.java
Labels: BE, ✨ feature, 🐙 BE - 신지수

#189 [Feat/#159] 이동 경로 좌표를 저장할 Entity 생성
  backend/src/main/java/hyfive/gachita/book/Book.java
  backend/src/main/java/hyfive/gachita/car/repository/CustomCarRepositoryImpl.java
  backend/src/main/java/hyfive/gachita/node/Node.java
  backend/src/main/java/hyfive/gachita/path/PathRepository.java
  backend/src/main/java/hyfive/gachita/path/domain/Path.java
  backend/src/main/java/hyfive/gachita/path/domain/PathSegment.java
  backend/src/main/java/hyfive/gachita/path/domain/Point.java
Labels: BE, ✨ feature, 🦦 BE - 성유진

#202 [Feat/#200] 미배차 차량 배차 알고리즘 provider 생성
  backend/src/main/java/hyfive/gachita/dispatch/UnDispatchService.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/CenterDispatchLocationDto.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/DispatchLocation.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/FilterDto.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/InitPathDto.java
  backend/src/main/java/hyfive/gachita/dispatch/module/filter/BoundingBoxFilter.java
  backend/src/main/java/hyfive/gachita/dispatch/module/filter/Filter.java
  backend/src/main/java/hyfive/gachita/dispatch/module/filter/HaversineFilter.java
  backend/src/main/java/hyfive/gachita/dispatch/provider/DispatchLocationProvider.java
  backend/src/main/java/hyfive/gachita/dispatch/provider/InitPathProvider.java
Labels: BE, ✨ feature, 🐙 BE - 신지수

#212 [Feat/#208] kakao api 데이터 추가
  backend/src/main/java/hyfive/gachita/client/kakao/KakaoNaviService.java
  backend/src/main/java/hyfive/gachita/client/kakao/RouteInfo.java
  backend/src/main/java/hyfive/gachita/client/kakao/dto/response/KakaoNaviRes.java
Labels: BE, ✨ feature, 🦦 BE - 성유진

#210 [Chore/#198] S3 설정 변경
  backend/src/main/java/hyfive/gachita/car/S3Service.java
  backend/src/main/java/hyfive/gachita/docs/RentalDocs.java
  backend/src/main/resources/application-init.properties
  backend/src/main/resources/application-prod.properties
Labels: BE, ⚙️ chore, 🐿️ FE - 김민정, 🐙 BE - 신지수

#213 [Feat/#204] 차량 수정 기능 구현
  frontend/src/components/Button.tsx
  frontend/src/features/carUploader/ImageInput.tsx
  frontend/src/features/carUploader/ImageValidator.util.ts
  frontend/src/features/carUploader/InputSection.tsx
  frontend/src/features/carUploader/useCarForm.ts
  frontend/src/features/carUploader/usePreviewImage.ts
  frontend/src/features/carUploader/useUploadImage.ts
  frontend/src/pages/center/CenterEditPage.tsx
  frontend/src/pages/center/CenterPage.tsx
  frontend/src/pages/index.ts
  frontend/src/routes/index.tsx
Labels: FE, ✨ feature, 🐿️ FE - 김민정

#215 [Feat/#195] 시간표 컴포넌트 리팩토링 / 수정 + 삭제 로직 추가
  frontend/src/features/calender/Calender.util.ts
  frontend/src/features/timeTable/GridConverter.ts
  frontend/src/features/timeTable/TimeTable.style.ts
  frontend/src/features/timeTable/TimeTable.test.tsx
  frontend/src/features/timeTable/components/AvailableTimeSlot.tsx
  frontend/src/features/timeTable/components/AvailableTimeSlots.tsx
  frontend/src/features/timeTable/components/TimeCell.tsx
  frontend/src/features/timeTable/components/TimeCells.tsx
  frontend/src/features/timeTable/components/TimeLabels.tsx
  frontend/src/features/timeTable/components/TimeTable.tsx
  frontend/src/features/timeTable/components/TimeTableHeader.tsx
  frontend/src/features/timeTable/hooks/useDocumentMouseEvent.ts
  frontend/src/features/timeTable/hooks/useTimeTableDrag.ts
  frontend/src/features/timeTable/hooks/useTimeTableDragState.ts
  frontend/src/features/timeTable/hooks/useTimeTableSlots.ts
  frontend/src/features/timeTable/services/dragHandlers.ts
  frontend/src/features/timeTable/services/slotMerger.ts
  frontend/src/features/timeTable/services/slotValidator.ts
  frontend/src/features/timeTable/useTimeTableDrag.ts
  frontend/src/features/timeTable/utils/TimeTable.util.ts
  frontend/src/features/timeTable/utils/slotUtils.ts
Labels: FE, ✨ feature, ♻️ refactor, 🐤 FE - 유재민

#261 [Feat/#241] 센터 - 메인 페이지 퍼블리싱
  frontend/src/assets/icons/edit_white.svg
  frontend/src/assets/icons/index.ts
  frontend/src/components/MonoButton.tsx
  frontend/src/features/calender/Calender.util.ts
  frontend/src/features/car/CarAddCard.tsx
  frontend/src/features/car/CarInfoCard.style.ts
  frontend/src/hooks/useCenterNavigation.ts
  frontend/src/pages/center/CenterPage.tsx
Labels: FE, ✨ feature, 🐤 FE - 유재민

#270 [Feat/#262] 센터 페이지 모달 제작
  frontend/src/assets/icons/Info-gray.svg
  frontend/src/assets/icons/index.ts
  frontend/src/components/Button.tsx
  frontend/src/components/CarModalContent.tsx
  frontend/src/components/Modal.tsx
  frontend/src/components/ModalContent.tsx
  frontend/src/hooks/useCenterModal.tsx
  frontend/src/layouts/CenterLayout.tsx
  frontend/src/pages/center/CenterPage.tsx
Labels: FE, ✨ feature, 🐤 FE - 유재민

#272 [Feat/#151] API 연동: 실시간 예약 현황
  frontend/eslint.config.js
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/App.tsx
  frontend/src/apis/BookAPI.ts
  frontend/src/components/EmptyUI.tsx
  frontend/src/components/FallbackUI.tsx
  frontend/src/features/book/Book.types.ts
  frontend/src/features/book/BookCard.style.ts
  frontend/src/features/book/BookCard.tsx
  frontend/src/features/book/BookDetailSection.tsx
  frontend/src/features/book/BookListSection.tsx
  frontend/src/features/book/BookSection.tsx
  frontend/src/features/map/useVisualizeMarker.ts
  frontend/src/features/refetchTimer/RefetchButton.tsx
  frontend/src/features/refetchTimer/rotateAnimation.util.ts
  frontend/src/features/schedule/ScheduleListSection.tsx
  frontend/src/mocks/bookMocks.ts
  frontend/src/pages/admin/book/BookPage.tsx
  frontend/src/types/bookType.types.ts
  frontend/src/utils/APIMatcher.ts
  frontend/src/utils/AxiosInstance.ts
  frontend/src/utils/CustomError.ts
  frontend/src/utils/TabMatcher.ts
Labels: FE, ✨ feature, 🐿️ FE - 김민정

#269 [Chore/#268] 에러 로그 디렉터리 생성 및 애플리케이션 실행에 따른 생성 파일 분리
  backend/scripts/deploy.sh
Labels: BE, ⚙️ chore, 🐙 BE - 신지수

#271 [Fix/#267] 신규 경로 배차 알고리즘 수정
  backend/src/main/java/hyfive/gachita/application/center/repository/CustomCenterRepositoryImpl.java
  backend/src/main/java/hyfive/gachita/application/node/NodeType.java
  backend/src/main/java/hyfive/gachita/client/ApiClientConfig.java
  backend/src/main/java/hyfive/gachita/dispatch/NewPathDispatchFlow.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/CarScheduleDto.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/FilteredCenterDto.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/FinalNewPathDto.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/NewBookDto.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/NewPathDto.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/NewPathNodeDto.java
  backend/src/main/java/hyfive/gachita/dispatch/module/checker/FinalNewPathChecker.java
  backend/src/main/java/hyfive/gachita/dispatch/module/condition/CenterCondition.java
  backend/src/main/java/hyfive/gachita/dispatch/module/filter/BoundingBoxFilter.java
  backend/src/main/java/hyfive/gachita/dispatch/module/filter/CarSelector.java
  backend/src/main/java/hyfive/gachita/dispatch/module/filter/HaversineFilter.java
  backend/src/main/java/hyfive/gachita/dispatch/module/provider/CenterListProvider.java
  backend/src/main/java/hyfive/gachita/dispatch/module/provider/IdleCarListProvider.java
  backend/src/main/java/hyfive/gachita/dispatch/module/provider/RouteInfoProvider.java
  backend/src/main/resources/rental.sql
Labels: BE, 🛠️ fix, 🦦 BE - 성유진

#277 [Feat/#265] 실시간 예약 현황에 경로 정보 추가
  backend/src/main/java/hyfive/gachita/application/book/BookController.java
  backend/src/main/java/hyfive/gachita/application/book/BookService.java
  backend/src/main/java/hyfive/gachita/application/book/dto/BookWithPathRes.java
  backend/src/main/java/hyfive/gachita/application/book/repository/CustomBookRepository.java
  backend/src/main/java/hyfive/gachita/application/book/repository/CustomBookRepositoryImpl.java
  backend/src/main/java/hyfive/gachita/application/path/PathService.java
  backend/src/main/java/hyfive/gachita/application/path/dto/PathRes.java
  backend/src/main/java/hyfive/gachita/application/path/respository/CustomPathRepository.java
  backend/src/main/java/hyfive/gachita/application/path/respository/CustomPathRepositoryImpl.java
  backend/src/main/java/hyfive/gachita/dispatch/DispatchService.java
  backend/src/main/java/hyfive/gachita/dispatch/NewPathDispatchFlow.java
  backend/src/main/java/hyfive/gachita/docs/BookDocs.java
Labels: BE, ✨ feature, 🦦 BE - 성유진

#278 [Feat/#205] API 연동: 차량 등록 및 수정
  frontend/src/apis/CarAPI.ts
  frontend/src/components/ModalContent.tsx
  frontend/src/features/carUploader/InputSection.tsx
  frontend/src/features/carUploader/useCarForm.ts
  frontend/src/hooks/useCenterNavigation.ts
  frontend/src/utils/AxiosInstance.ts
  frontend/src/utils/CustomError.ts
Labels: FE, ✨ feature, 🐿️ FE - 김민정

#276 [Feat/#255] 신규 경로 배차 알고리즘 완료 시, 데이터베이스에 저장
  backend/src/main/java/hyfive/gachita/application/book/Book.java
  backend/src/main/java/hyfive/gachita/application/book/BookController.java
  backend/src/main/java/hyfive/gachita/application/book/BookService.java
  backend/src/main/java/hyfive/gachita/application/book/dto/BookWithPathRes.java
  backend/src/main/java/hyfive/gachita/application/book/repository/CustomBookRepository.java
  backend/src/main/java/hyfive/gachita/application/book/repository/CustomBookRepositoryImpl.java
  backend/src/main/java/hyfive/gachita/application/center/repository/CustomCenterRepositoryImpl.java
  backend/src/main/java/hyfive/gachita/application/node/Node.java
  backend/src/main/java/hyfive/gachita/application/path/Path.java
  backend/src/main/java/hyfive/gachita/application/path/PathService.java
  backend/src/main/java/hyfive/gachita/application/path/dto/PathRes.java
  backend/src/main/java/hyfive/gachita/application/path/respository/CustomPathRepository.java
  backend/src/main/java/hyfive/gachita/application/path/respository/CustomPathRepositoryImpl.java
  backend/src/main/java/hyfive/gachita/dispatch/DispatchFlowSelector.java
  backend/src/main/java/hyfive/gachita/dispatch/DispatchService.java
  backend/src/main/java/hyfive/gachita/dispatch/NewPathDispatchFlow.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/CarScheduleDto.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/FinalNewPathDto.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/NodeDto.java
  backend/src/main/java/hyfive/gachita/dispatch/module/checker/FinalNewPathChecker.java
  backend/src/main/java/hyfive/gachita/dispatch/module/condition/PathCondition.java
  backend/src/main/java/hyfive/gachita/dispatch/module/provider/RouteInfoProvider.java
  backend/src/main/java/hyfive/gachita/docs/BookDocs.java
Labels: BE, ✨ feature, 🦦 BE - 성유진

#284 [Fix/#264] 예약 데이터 주소 형식 수정
  backend/src/main/resources/book.sql
  backend/src/main/resources/center.sql
Labels: BE, 🛠️ fix, 🦦 BE - 성유진

#286 [Feat/#225] 실시간 경로 카드 스크롤 조회
  backend/src/main/java/hyfive/gachita/application/path/PathController.java
  backend/src/main/java/hyfive/gachita/application/path/PathService.java
  backend/src/main/java/hyfive/gachita/application/path/dto/PathCursor.java
  backend/src/main/java/hyfive/gachita/application/path/dto/PathDetailRes.java
  backend/src/main/java/hyfive/gachita/application/path/respository/CustomPathRepository.java
  backend/src/main/java/hyfive/gachita/application/path/respository/CustomPathRepositoryImpl.java
  backend/src/main/java/hyfive/gachita/docs/PathDocs.java
Labels: BE, ✨ feature, 🦦 BE - 성유진

#287 [Feat/#232] 경로에 따른 탑승자 정보를 제공
  backend/src/main/java/hyfive/gachita/application/book/Book.java
  backend/src/main/java/hyfive/gachita/application/path/Path.java
  backend/src/main/java/hyfive/gachita/application/path/PathController.java
  backend/src/main/java/hyfive/gachita/application/path/PathService.java
  backend/src/main/java/hyfive/gachita/application/path/dto/PassengerRes.java
  backend/src/main/java/hyfive/gachita/application/path/respository/CustomPathRepository.java
  backend/src/main/java/hyfive/gachita/application/path/respository/CustomPathRepositoryImpl.java
  backend/src/main/java/hyfive/gachita/docs/PathDocs.java
Labels: BE, ✨ feature, 🦦 BE - 성유진

#288 [QA/#173] 지도 이동 최적화: 위치 복귀, 축소 제한
  frontend/src/components/RefetchButton.tsx
  frontend/src/components/layouts/Header.tsx
  frontend/src/features/book/BookListSection.tsx
  frontend/src/features/map/Map.types.ts
  frontend/src/features/map/MapContent.tsx
  frontend/src/features/map/MidPointButton.tsx
  frontend/src/features/map/ZoomButton.tsx
  frontend/src/features/map/useInitializeMap.ts
  frontend/src/features/map/useZoomLevel.ts
  frontend/src/features/schedule/ScheduleListSection.tsx
  frontend/src/pages/admin/DriversPage.tsx
  frontend/src/pages/admin/centers/CentersPage.tsx
  frontend/src/pages/index.ts
  frontend/src/routes/index.tsx
  frontend/src/utils/RotateAnimation.ts
Labels: FE, 🐿️ FE - 김민정, ⚡️ QA

#296 [Feat/#227] 지도 그리기 데이터 API 수정
  backend/src/main/java/hyfive/gachita/application/node/repository/CustomNodeRepositoryImpl.java
  backend/src/main/java/hyfive/gachita/application/path/PathService.java
  backend/src/main/java/hyfive/gachita/application/path/dto/MarkerRes.java
  backend/src/main/resources/application-init.properties
Labels: BE, ♻️ refactor, ⚙️ chore, 🐙 BE - 신지수

#295 [Feat/#282] Kakao 장소 검색 API 연동
  frontend/src/apis/KakaoSearchAPI.ts
  frontend/src/components/Input.tsx
  frontend/src/components/LoadingSpinner.tsx
  frontend/src/features/addressInput/AddressDropdown.tsx
  frontend/src/features/addressInput/AddressInput.style.ts
  frontend/src/features/addressInput/AddressInput.tsx
  frontend/src/features/addressInput/useAddressSearch.ts
  frontend/src/hooks/useDebounce.ts
  frontend/src/types/kakaoSearch.types.ts
  frontend/src/utils/RotateAnimation.ts
Labels: FE, ✨ feature, 🐤 FE - 유재민

#300 [Feat/#299] 예약자 등록 폼 제출 / 유효성 검증 로직 추가
  frontend/src/components/LoadingSpinner.tsx
  frontend/src/features/addressInput/AddressInput.tsx
  frontend/src/features/calender/Calender.util.ts
  frontend/src/features/timePicker/TimePicker.tsx
  frontend/src/features/userRegister/UserInputSection.tsx
  frontend/src/features/userRegister/UserRegister.types.ts
  frontend/src/layouts/AdminLayout.tsx
  frontend/src/utils/UserValidation.ts
Labels: FE, ✨ feature, 🐤 FE - 유재민

#301 [Refactor/#298] 지도 그리기 API 리팩터링
  backend/src/main/java/hyfive/gachita/application/node/Node.java
  backend/src/main/java/hyfive/gachita/application/node/repository/CustomNodeRepository.java
  backend/src/main/java/hyfive/gachita/application/node/repository/CustomNodeRepositoryImpl.java
  backend/src/main/java/hyfive/gachita/application/path/PathService.java
  backend/src/main/java/hyfive/gachita/application/path/dto/HighlightRes.java
  backend/src/main/java/hyfive/gachita/application/path/dto/MarkerRes.java
  backend/src/main/java/hyfive/gachita/application/path/dto/SegmentRes.java
  backend/src/main/java/hyfive/gachita/application/path/respository/CustomPathRepository.java
  backend/src/main/java/hyfive/gachita/application/path/respository/CustomPathRepositoryImpl.java
  backend/src/main/java/hyfive/gachita/docs/PathDocs.java
Labels: BE, ♻️ refactor, 🦦 BE - 성유진

#304 [Feat/#302] 확정된 경로의 좌표를 데이터베이스에 반영
  backend/src/main/java/hyfive/gachita/application/node/Node.java
  backend/src/main/java/hyfive/gachita/application/node/Point.java
  backend/src/main/java/hyfive/gachita/application/node/Segment.java
  backend/src/main/java/hyfive/gachita/application/path/PathService.java
  backend/src/main/java/hyfive/gachita/application/path/dto/HighlightRes.java
  backend/src/main/java/hyfive/gachita/application/path/respository/CustomPathRepository.java
  backend/src/main/java/hyfive/gachita/application/path/respository/CustomPathRepositoryImpl.java
  backend/src/main/java/hyfive/gachita/client/kakao/KakaoNaviService.java
  backend/src/main/java/hyfive/gachita/demo/DemoController.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/FilteredPathDto.java
  backend/src/main/java/hyfive/gachita/global/GlobalExceptionHandler.java
Labels: BE, ✨ feature, 🦦 BE - 성유진

#308 [Feat/#291] 기존 경로 배차 알고리즘 부착
  backend/src/main/java/hyfive/gachita/application/center/repository/CustomCenterRepositoryImpl.java
  backend/src/main/java/hyfive/gachita/application/path/Path.java
  backend/src/main/java/hyfive/gachita/application/path/PathService.java
  backend/src/main/java/hyfive/gachita/application/path/dto/NodeWithDeadline.java
  backend/src/main/java/hyfive/gachita/application/path/respository/CustomPathRepositoryImpl.java
  backend/src/main/java/hyfive/gachita/dispatch/DispatchFlowSelector.java
  backend/src/main/java/hyfive/gachita/dispatch/DispatchService.java
  backend/src/main/java/hyfive/gachita/dispatch/NewPathDispatchFlow.java
  backend/src/main/java/hyfive/gachita/dispatch/OldPathDispatchFlow.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/DispatchResult.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/FilteredPathDto.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/FinalNewPathDto.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/FinalOldPathDto.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/NodeDto.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/OldPathDto.java
  backend/src/main/java/hyfive/gachita/dispatch/module/calculator/InsertNodeCalculator.java
  backend/src/main/java/hyfive/gachita/global/ErrorCode.java
Labels: BE, ✨ feature, 🐙 BE - 신지수

#330 [Chore/#238] SSL 관련 설정 추가
  backend/src/main/java/hyfive/gachita/config/WebConfig.java
  backend/src/main/resources/application-init.properties
  backend/src/main/resources/application-prod.properties
Labels: BE, ⚙️ chore, 🦦 BE - 성유진

#327 [Feat/#247] 시간표 컴포넌트 등록 API 연결
  frontend/src/apis/TimeTableAPI.ts
  frontend/src/features/timeTable/TimeTable.style.ts
  frontend/src/features/timeTable/TimeTable.test.tsx
  frontend/src/features/timeTable/TimeTable.type.ts
  frontend/src/features/timeTable/components/ActionButtonGroup.tsx
  frontend/src/features/timeTable/components/TimeTable.tsx
  frontend/src/pages/center/CenterPage.tsx
Labels: FE, ✨ feature, 🐤 FE - 유재민

#333 fix : 예약 내역 리스트에 pathId 추가
  backend/src/main/java/hyfive/gachita/application/book/BookService.java
  backend/src/main/java/hyfive/gachita/application/book/dto/BookRes.java
  backend/src/main/java/hyfive/gachita/application/book/repository/CustomBookRepositoryImpl.java
Labels: BE, 🛠️ fix, 🐙 BE - 신지수

#337 [Feat/#244-5] 예약자 관리 페이지 / 운행 경로 관리 페이지 API 연동
  frontend/src/apis/BookAPI.ts
  frontend/src/apis/RouteListAPI.ts
  frontend/src/components/Pagination.tsx
  frontend/src/pages/admin/book/PathsPage.tsx
  frontend/src/pages/admin/book/UsersPage.tsx
  frontend/src/types/routeType.types.ts
  frontend/src/utils/APIMatcher.ts
Labels: FE, ✨ feature, 🐤 FE - 유재민

#341 [Merger] v2.2.0 Backend 병합
  backend/src/main/java/hyfive/gachita/GachitaApplication.java
  backend/src/main/java/hyfive/gachita/config/WebConfig.java
  backend/src/main/java/hyfive/gachita/dispatch/DispatchFlowSelector.java
  backend/src/main/java/hyfive/gachita/dispatch/NewPathDispatchFlow.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/RadiusPolicy.java
  backend/src/main/java/hyfive/gachita/dispatch/module/calculator/RadiusExpandCalculator.java
  backend/src/main/resources/application-init.properties
  backend/src/main/resources/application-prod.properties
Labels: BE

#348 [Merger] v2.2.1 Backend 병합
  backend/src/main/java/hyfive/gachita/application/center/repository/CustomCenterRepositoryImpl.java
  backend/src/main/java/hyfive/gachita/application/path/Path.java
  backend/src/main/java/hyfive/gachita/application/path/PathService.java
  backend/src/main/java/hyfive/gachita/application/rental/AvailableRental.java
  backend/src/main/java/hyfive/gachita/application/rental/AvailableRentalRepository.java
  backend/src/main/java/hyfive/gachita/application/rental/Rental.java
  backend/src/main/java/hyfive/gachita/application/rental/RentalService.java
  backend/src/main/java/hyfive/gachita/application/rental/repository/CustomRentalRepositoryImpl.java
  backend/src/main/java/hyfive/gachita/dispatch/FragmentDto.java
  backend/src/main/java/hyfive/gachita/dispatch/NewPathDispatchFlow.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/CarScheduleDto.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/FinalNewPathDto.java
  backend/src/main/java/hyfive/gachita/dispatch/module/checker/FinalNewPathChecker.java
  backend/src/main/resources/available-rental.sql
  backend/src/main/resources/rental.sql
Labels: BE

#342 [Feat/#340] 예약자 관리 페이지에서 pathId로 운행 경로 페이지 라우팅
  frontend/src/apis/RouteListAPI.ts
  frontend/src/components/table/TableWithIndex.tsx
  frontend/src/pages/admin/book/PathsPage.tsx
  frontend/src/pages/admin/book/UsersPage.tsx
Labels: FE, ✨ feature, 🐤 FE - 유재민

#346 [Feat/#292-343] Polling 기능 구현
  frontend/src/apis/BookAPI.ts
  frontend/src/apis/ScheduleAPI.ts
  frontend/src/components/RefetchButton.tsx
  frontend/src/features/book/Book.types.ts
  frontend/src/features/book/BookCard.style.ts
  frontend/src/features/book/BookDetailSection.tsx
  frontend/src/features/book/BookListSection.tsx
  frontend/src/features/book/BookSection.tsx
  frontend/src/features/schedule/Schedule.types.ts
  frontend/src/features/schedule/ScheduleDataFetcher.tsx
  frontend/src/features/schedule/ScheduleListSection.tsx
  frontend/src/utils/APIMatcher.ts
Labels: FE, ✨ feature, 🐿️ FE - 김민정

#353 [Chore/#352] 불필요한 주석 삭제
  backend/src/main/java/hyfive/gachita/application/path/Path.java
  backend/src/main/java/hyfive/gachita/application/rental/RentalService.java
  backend/src/main/java/hyfive/gachita/dispatch/DispatchFlowSelector.java
  backend/src/main/java/hyfive/gachita/dispatch/NewPathDispatchFlow.java
  backend/src/main/java/hyfive/gachita/dispatch/dto/FragmentDto.java
  backend/src/main/java/hyfive/gachita/dispatch/module/checker/FinalNewPathChecker.java
Labels: BE, ⚙️ chore, 🐙 BE - 신지수

#349 [Fix/#344] 드래그 오류 수정 / 윗쪽 드래그 기능 지원
  frontend/src/assets/icons/close.svg
  frontend/src/features/timeTable/TimeTable.test.tsx
  frontend/src/features/timeTable/components/AvailableTimeSlot.tsx
  frontend/src/features/timeTable/components/TimeTable.tsx
  frontend/src/features/timeTable/hooks/useTimeTableSlots.ts
  frontend/src/features/timeTable/services/dragHandlers.ts
Labels: FE, ✨ feature, 🛠️ fix, 🐤 FE - 유재민, ⚡️ QA

#355 [Feat/#280] 경로 운행 상태 변경 API
  backend/src/main/java/hyfive/gachita/application/path/PathService.java
  backend/src/main/java/hyfive/gachita/demo/DemoController.java
  backend/src/main/java/hyfive/gachita/demo/DemoService.java
Labels: BE, ✨ feature, 🦦 BE - 성유진

#363 [Fix/#362] 해상도 비율 수정 (100% 기준 레이아웃 정상화)
  frontend/src/components/CarModalContent.tsx
  frontend/src/components/ModalContent.tsx
  frontend/src/features/book/BookListSection.tsx
  frontend/src/features/schedule/ScheduleListSection.tsx
  frontend/src/layouts/AdminLayout.tsx
  frontend/src/layouts/BookLayout.tsx
  frontend/src/layouts/CenterLayout.tsx
  frontend/src/pages/LandingPage.tsx
  frontend/src/pages/admin/centers/CenterDetailPage.tsx
  frontend/src/pages/center/CenterPage.tsx
  frontend/src/styles/global.style.css
Labels: FE, 🛠️ fix, 🐤 FE - 유재민, 🐿️ FE - 김민정

#372 [Fix/#370] 백엔드 qa 반영
  backend/src/main/java/hyfive/gachita/application/car/CarService.java
  backend/src/main/java/hyfive/gachita/application/car/dto/CarListRes.java
  backend/src/main/java/hyfive/gachita/application/car/dto/CarRes.java
  backend/src/main/java/hyfive/gachita/application/car/dto/UpdateCarReq.java
  backend/src/main/java/hyfive/gachita/application/path/dto/PathDetailRes.java
  backend/src/main/java/hyfive/gachita/application/path/dto/PathRes.java
  backend/src/main/java/hyfive/gachita/dispatch/module/calculator/InsertNodeCalculator.java
Labels: BE, 🛠️ fix, 🐙 BE - 신지수, ⚡️ QA

#377 [Merge] v3.0.2 Backend 병합
  backend/scripts/deploy.sh
  backend/src/main/java/hyfive/gachita/application/path/PathService.java
  backend/src/main/java/hyfive/gachita/application/path/dto/BoundRes.java
  backend/src/main/java/hyfive/gachita/application/path/dto/MapDrawRes.java
  backend/src/main/java/hyfive/gachita/client/kakao/KakaoNaviService.java
  backend/src/main/java/hyfive/gachita/client/kakao/RouteInfo.java
  backend/src/main/java/hyfive/gachita/client/kakao/dto/response/KakaoNaviRes.java
Labels: BE, 🐙 BE - 신지수, 🦦 BE - 성유진

#380 [Docs/#379] README v.2 작성
  README.md
Labels: BE, FE, 📝 docs, 🐤 FE - 유재민, 🐿️ FE - 김민정, 🐙 BE - 신지수, 🦦 BE - 성유진

#388 [HotFix#387] 시간 유효성 검증 버그 수정
  frontend/src/components/Input.tsx
  frontend/src/features/addressInput/AddressInput.tsx
  frontend/src/features/book/BookCard.tsx
  frontend/src/features/timePicker/TimePicker.tsx
  frontend/src/utils/UserValidation.ts
Labels: FE, 🐤 FE - 유재민, ⚡️ QA, 🔥 hotfix

#389 [Chore] dev 브랜치로 즉시 병합된 hotFix 커밋을 dev-fe에 반영
  frontend/src/components/Input.tsx
  frontend/src/features/addressInput/AddressInput.tsx
  frontend/src/features/book/BookCard.tsx
  frontend/src/features/timePicker/TimePicker.tsx
  frontend/src/utils/UserValidation.ts
Labels: FE, ⚙️ chore, 🐤 FE - 유재민

#390 [Docs] Readme version 3
  README.md
Labels: 📝 docs
